/// Built-in CLI completion specs, embedded at compile time via build.rs.
///
/// Tier 1 specs (top ~70 commands) are embedded via include_str!().
/// Tier 2 specs (600+ commands) are loaded from disk at runtime by the app.
use std::collections::HashMap;

use crate::spec::CliSpec;

// Generated by build.rs — scans specs/*.json and creates include_str!() entries.
include!(concat!(env!("OUT_DIR"), "/generated_specs.rs"));

/// Load all embedded (Tier 1) CLI specs into a HashMap keyed by command name.
pub fn load_all_specs() -> HashMap<String, CliSpec> {
    let mut specs = HashMap::new();

    for raw in all_spec_strings() {
        match serde_json::from_str::<CliSpec>(raw) {
            Ok(spec) => {
                for alias in &spec.aliases {
                    specs.insert(alias.clone(), spec.clone());
                }
                specs.insert(spec.name.clone(), spec);
            }
            Err(e) => {
                let preview: String = raw.chars().take(60).collect();
                log::warn!("Failed to parse CLI spec ({}…): {}", preview, e);
            }
        }
    }

    specs
}

#[cfg(test)]
mod tests {
    use super::*;

    #[test]
    fn test_load_all_specs() {
        let specs = load_all_specs();
        assert!(
            specs.len() >= 50,
            "Expected 50+ embedded specs, got {}",
            specs.len()
        );
        assert!(specs.contains_key("git"));
        assert!(specs.contains_key("cargo"));
        assert!(specs.contains_key("docker"));
        assert!(specs.contains_key("npm"));
        assert!(specs.contains_key("kubectl"));

        let git = &specs["git"];
        assert!(!git.subcommands.is_empty());
        assert!(git.find_subcommand("commit").is_some());

        let cargo = &specs["cargo"];
        assert!(cargo.find_subcommand("build").is_some());
    }
}
