mod accent;
mod colors;
mod fallback;
mod global;
mod players;
mod refinement;
mod registry;
mod scale;
mod status;
mod syntax;
mod theme;

pub use accent::AccentColors;
pub use colors::ThemeColors;
pub use fallback::fallback_theme;
pub use global::{ActiveTheme, GlobalTheme};
pub use players::{PlayerColor, PlayerColors};
pub use refinement::ThemeColorsRefinement;
pub use registry::{ThemeMeta, ThemeRegistry};
pub use scale::{ColorScale, ColorScaleStep};
pub use status::{StatusColors, StatusStyle};
pub use syntax::SyntaxTheme;
pub use theme::{Appearance, Theme, ThemeFamily, ThemeStyles};
