use inazuma::Oklch;

use crate::colors::ThemeColors;

/// A refinement layer for ThemeColors where every field is optional.
///
/// Used to override specific colors in a base theme without replacing all values.
#[derive(Clone, Debug, Default)]
pub struct ThemeColorsRefinement {
    pub border: Option<Oklch>,
    pub border_variant: Option<Oklch>,
    pub border_focused: Option<Oklch>,
    pub border_selected: Option<Oklch>,
    pub border_transparent: Option<Oklch>,
    pub border_disabled: Option<Oklch>,
    pub elevated_surface_background: Option<Oklch>,
    pub surface_background: Option<Oklch>,
    pub background: Option<Oklch>,
    pub element_background: Option<Oklch>,
    pub element_hover: Option<Oklch>,
    pub element_active: Option<Oklch>,
    pub element_selected: Option<Oklch>,
    pub element_selection_background: Option<Oklch>,
    pub element_disabled: Option<Oklch>,
    pub drop_target_background: Option<Oklch>,
    pub drop_target_border: Option<Oklch>,
    pub ghost_element_background: Option<Oklch>,
    pub ghost_element_hover: Option<Oklch>,
    pub ghost_element_active: Option<Oklch>,
    pub ghost_element_selected: Option<Oklch>,
    pub ghost_element_disabled: Option<Oklch>,
    pub text: Option<Oklch>,
    pub text_muted: Option<Oklch>,
    pub text_placeholder: Option<Oklch>,
    pub text_disabled: Option<Oklch>,
    pub text_accent: Option<Oklch>,
    pub icon: Option<Oklch>,
    pub icon_muted: Option<Oklch>,
    pub icon_disabled: Option<Oklch>,
    pub icon_placeholder: Option<Oklch>,
    pub icon_accent: Option<Oklch>,
    pub status_bar_background: Option<Oklch>,
    pub title_bar_background: Option<Oklch>,
    pub title_bar_inactive_background: Option<Oklch>,
    pub toolbar_background: Option<Oklch>,
    pub tab_bar_background: Option<Oklch>,
    pub tab_inactive_background: Option<Oklch>,
    pub tab_active_background: Option<Oklch>,
    pub search_match_background: Option<Oklch>,
    pub search_active_match_background: Option<Oklch>,
    pub panel_background: Option<Oklch>,
    pub panel_focused_border: Option<Oklch>,
    pub panel_indent_guide: Option<Oklch>,
    pub panel_indent_guide_hover: Option<Oklch>,
    pub panel_indent_guide_active: Option<Oklch>,
    pub panel_overlay_background: Option<Oklch>,
    pub panel_overlay_hover: Option<Oklch>,
    pub pane_focused_border: Option<Oklch>,
    pub pane_group_border: Option<Oklch>,
    pub scrollbar_thumb_background: Option<Oklch>,
    pub scrollbar_thumb_hover_background: Option<Oklch>,
    pub scrollbar_thumb_active_background: Option<Oklch>,
    pub scrollbar_thumb_border: Option<Oklch>,
    pub scrollbar_track_background: Option<Oklch>,
    pub scrollbar_track_border: Option<Oklch>,
    pub editor_foreground: Option<Oklch>,
    pub editor_background: Option<Oklch>,
    pub editor_gutter_background: Option<Oklch>,
    pub editor_subheader_background: Option<Oklch>,
    pub editor_active_line_background: Option<Oklch>,
    pub editor_highlighted_line_background: Option<Oklch>,
    pub editor_line_number: Option<Oklch>,
    pub editor_active_line_number: Option<Oklch>,
    pub editor_invisible: Option<Oklch>,
    pub editor_wrap_guide: Option<Oklch>,
    pub editor_active_wrap_guide: Option<Oklch>,
    pub editor_indent_guide: Option<Oklch>,
    pub editor_indent_guide_active: Option<Oklch>,
    pub editor_document_highlight_read_background: Option<Oklch>,
    pub editor_document_highlight_write_background: Option<Oklch>,
    pub editor_document_highlight_bracket_background: Option<Oklch>,
    pub terminal_background: Option<Oklch>,
    pub terminal_foreground: Option<Oklch>,
    pub terminal_bright_foreground: Option<Oklch>,
    pub terminal_dim_foreground: Option<Oklch>,
    pub terminal_accent: Option<Oklch>,
    pub terminal_ansi_background: Option<Oklch>,
    pub terminal_ansi_black: Option<Oklch>,
    pub terminal_ansi_bright_black: Option<Oklch>,
    pub terminal_ansi_dim_black: Option<Oklch>,
    pub terminal_ansi_red: Option<Oklch>,
    pub terminal_ansi_bright_red: Option<Oklch>,
    pub terminal_ansi_dim_red: Option<Oklch>,
    pub terminal_ansi_green: Option<Oklch>,
    pub terminal_ansi_bright_green: Option<Oklch>,
    pub terminal_ansi_dim_green: Option<Oklch>,
    pub terminal_ansi_yellow: Option<Oklch>,
    pub terminal_ansi_bright_yellow: Option<Oklch>,
    pub terminal_ansi_dim_yellow: Option<Oklch>,
    pub terminal_ansi_blue: Option<Oklch>,
    pub terminal_ansi_bright_blue: Option<Oklch>,
    pub terminal_ansi_dim_blue: Option<Oklch>,
    pub terminal_ansi_magenta: Option<Oklch>,
    pub terminal_ansi_bright_magenta: Option<Oklch>,
    pub terminal_ansi_dim_magenta: Option<Oklch>,
    pub terminal_ansi_cyan: Option<Oklch>,
    pub terminal_ansi_bright_cyan: Option<Oklch>,
    pub terminal_ansi_dim_cyan: Option<Oklch>,
    pub terminal_ansi_white: Option<Oklch>,
    pub terminal_ansi_bright_white: Option<Oklch>,
    pub terminal_ansi_dim_white: Option<Oklch>,
    pub link_text_hover: Option<Oklch>,
    pub version_control_added: Option<Oklch>,
    pub version_control_deleted: Option<Oklch>,
    pub version_control_modified: Option<Oklch>,
    pub version_control_renamed: Option<Oklch>,
    pub version_control_conflict: Option<Oklch>,
    pub version_control_ignored: Option<Oklch>,
    pub version_control_word_added: Option<Oklch>,
    pub version_control_word_deleted: Option<Oklch>,
    pub version_control_conflict_marker_ours: Option<Oklch>,
    pub version_control_conflict_marker_theirs: Option<Oklch>,
    pub minimap_thumb_background: Option<Oklch>,
    pub minimap_thumb_hover_background: Option<Oklch>,
    pub minimap_thumb_active_background: Option<Oklch>,
    pub minimap_thumb_border: Option<Oklch>,
    pub vim_normal_background: Option<Oklch>,
    pub vim_insert_background: Option<Oklch>,
    pub vim_replace_background: Option<Oklch>,
    pub vim_visual_background: Option<Oklch>,
    pub vim_visual_line_background: Option<Oklch>,
    pub vim_visual_block_background: Option<Oklch>,
    pub vim_yank_background: Option<Oklch>,
    pub vim_helix_normal_background: Option<Oklch>,
    pub vim_helix_select_background: Option<Oklch>,
    pub vim_normal_foreground: Option<Oklch>,
    pub vim_insert_foreground: Option<Oklch>,
    pub vim_replace_foreground: Option<Oklch>,
    pub vim_visual_foreground: Option<Oklch>,
    pub vim_visual_line_foreground: Option<Oklch>,
    pub vim_visual_block_foreground: Option<Oklch>,
    pub vim_helix_normal_foreground: Option<Oklch>,
    pub vim_helix_select_foreground: Option<Oklch>,
    pub debugger_accent: Option<Oklch>,
    pub editor_debugger_active_line_background: Option<Oklch>,
    pub editor_hover_line_number: Option<Oklch>,
    pub block_success_badge: Option<Oklch>,
    pub block_error_badge: Option<Oklch>,
    pub block_running_badge: Option<Oklch>,
}

/// Macro to apply optional refinement fields to a ThemeColors struct.
macro_rules! apply_refinement {
    ($base:expr, $refinement:expr, $($field:ident),* $(,)?) => {
        ThemeColors {
            $( $field: $refinement.$field.unwrap_or($base.$field), )*
        }
    };
}

impl ThemeColorsRefinement {
    /// Applies this refinement to a base ThemeColors, returning a new ThemeColors
    /// with overridden values where present.
    pub fn apply_to(&self, base: &ThemeColors) -> ThemeColors {
        apply_refinement!(
            base,
            self,
            border,
            border_variant,
            border_focused,
            border_selected,
            border_transparent,
            border_disabled,
            elevated_surface_background,
            surface_background,
            background,
            element_background,
            element_hover,
            element_active,
            element_selected,
            element_selection_background,
            element_disabled,
            drop_target_background,
            drop_target_border,
            ghost_element_background,
            ghost_element_hover,
            ghost_element_active,
            ghost_element_selected,
            ghost_element_disabled,
            text,
            text_muted,
            text_placeholder,
            text_disabled,
            text_accent,
            icon,
            icon_muted,
            icon_disabled,
            icon_placeholder,
            icon_accent,
            status_bar_background,
            title_bar_background,
            title_bar_inactive_background,
            toolbar_background,
            tab_bar_background,
            tab_inactive_background,
            tab_active_background,
            search_match_background,
            search_active_match_background,
            panel_background,
            panel_focused_border,
            panel_indent_guide,
            panel_indent_guide_hover,
            panel_indent_guide_active,
            panel_overlay_background,
            panel_overlay_hover,
            pane_focused_border,
            pane_group_border,
            scrollbar_thumb_background,
            scrollbar_thumb_hover_background,
            scrollbar_thumb_active_background,
            scrollbar_thumb_border,
            scrollbar_track_background,
            scrollbar_track_border,
            editor_foreground,
            editor_background,
            editor_gutter_background,
            editor_subheader_background,
            editor_active_line_background,
            editor_highlighted_line_background,
            editor_line_number,
            editor_active_line_number,
            editor_invisible,
            editor_wrap_guide,
            editor_active_wrap_guide,
            editor_indent_guide,
            editor_indent_guide_active,
            editor_document_highlight_read_background,
            editor_document_highlight_write_background,
            editor_document_highlight_bracket_background,
            terminal_background,
            terminal_foreground,
            terminal_bright_foreground,
            terminal_dim_foreground,
            terminal_accent,
            terminal_ansi_background,

            terminal_ansi_black,
            terminal_ansi_bright_black,
            terminal_ansi_dim_black,
            terminal_ansi_red,
            terminal_ansi_bright_red,
            terminal_ansi_dim_red,
            terminal_ansi_green,
            terminal_ansi_bright_green,
            terminal_ansi_dim_green,
            terminal_ansi_yellow,
            terminal_ansi_bright_yellow,
            terminal_ansi_dim_yellow,
            terminal_ansi_blue,
            terminal_ansi_bright_blue,
            terminal_ansi_dim_blue,
            terminal_ansi_magenta,
            terminal_ansi_bright_magenta,
            terminal_ansi_dim_magenta,
            terminal_ansi_cyan,
            terminal_ansi_bright_cyan,
            terminal_ansi_dim_cyan,
            terminal_ansi_white,
            terminal_ansi_bright_white,
            terminal_ansi_dim_white,
            link_text_hover,
            version_control_added,
            version_control_deleted,
            version_control_modified,
            version_control_renamed,
            version_control_conflict,
            version_control_ignored,
            version_control_word_added,
            version_control_word_deleted,
            version_control_conflict_marker_ours,
            version_control_conflict_marker_theirs,
            minimap_thumb_background,
            minimap_thumb_hover_background,
            minimap_thumb_active_background,
            minimap_thumb_border,
            vim_normal_background,
            vim_insert_background,
            vim_replace_background,
            vim_visual_background,
            vim_visual_line_background,
            vim_visual_block_background,
            vim_yank_background,
            vim_helix_normal_background,
            vim_helix_select_background,
            vim_normal_foreground,
            vim_insert_foreground,
            vim_replace_foreground,
            vim_visual_foreground,
            vim_visual_line_foreground,
            vim_visual_block_foreground,
            vim_helix_normal_foreground,
            vim_helix_select_foreground,
            debugger_accent,
            editor_debugger_active_line_background,
            editor_hover_line_number,
            block_success_badge,
            block_error_badge,
            block_running_badge,
        )
    }
}
